<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>GpuParticle.Runtime</AssemblyName>
    <RootNamespace>GpuParticle.Runtime</RootNamespace>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(UnityEngineManaged)/UnityEngine.CoreModule.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(UnityEngineManaged)/UnityEngine.ParticleSystemModule.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
