<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>GpuParticle.Editor</AssemblyName>
    <RootNamespace>GpuParticle.Editor</RootNamespace>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Runtime/GpuParticle.Runtime.csproj" />
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(UnityEngineManaged)/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(UnityEngineManaged)/UnityEngine.ParticleSystemModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(UnityEngineManaged)/UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEditor.CoreModule">
      <HintPath>$(UnityEngineManaged)/UnityEditor.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
